/** biome-ignore-all lint/suspicious/noExplicitAny: REASON */
/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import { lazy } from "solid-js"

export const Index: Record<string, Record<string, any>> = {
  "v1": {
    "accordion": {
      name: "accordion",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/accordion.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/accordion.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "alert-dialog": {
      name: "alert-dialog",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [{
        path: "src/registry/v1/ui/alert-dialog.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/alert-dialog.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "alert": {
      name: "alert",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/alert.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/alert.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "aspect-ratio": {
      name: "aspect-ratio",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/aspect-ratio.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/aspect-ratio.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "avatar": {
      name: "avatar",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/avatar.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/avatar.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "badge": {
      name: "badge",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/badge.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/badge.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "Breadcrumb": {
      name: "Breadcrumb",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/breadcrumb.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/breadcrumb.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "button-group": {
      name: "button-group",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button","separator"],
      files: [{
        path: "src/registry/v1/ui/button-group.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/button-group.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "button": {
      name: "button",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/button.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/button.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "card": {
      name: "card",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/card.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/card.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "carousel": {
      name: "carousel",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [{
        path: "src/registry/v1/ui/carousel.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/carousel.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "checkbox": {
      name: "checkbox",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/checkbox.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/checkbox.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "collapsible": {
      name: "collapsible",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/collapsible.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/collapsible.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "combobox": {
      name: "combobox",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/combobox.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/combobox.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "command": {
      name: "command",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/command.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/command.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "context-menu": {
      name: "context-menu",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/context-menu.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/context-menu.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "dropdown-menu": {
      name: "dropdown-menu",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/dropdown-menu.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/dropdown-menu.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "empty": {
      name: "empty",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/empty.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/empty.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "field": {
      name: "field",
      description: "",
      type: "registry:ui",
      registryDependencies: ["label","separator"],
      files: [{
        path: "src/registry/v1/ui/field.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/field.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "hover-card": {
      name: "hover-card",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/hover-card.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/hover-card.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "input-group": {
      name: "input-group",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button","input","textarea"],
      files: [{
        path: "src/registry/v1/ui/input-group.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/input-group.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "input-otp": {
      name: "input-otp",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/input-otp.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/input-otp.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "input": {
      name: "input",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/input.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/input.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "item": {
      name: "item",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/item.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/item.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "kbd": {
      name: "kbd",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/kbd.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/kbd.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "label": {
      name: "label",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/label.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/label.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "menubar": {
      name: "menubar",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/menubar.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/menubar.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "native-select": {
      name: "native-select",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/native-select.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/native-select.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "navigation-menu": {
      name: "navigation-menu",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/navigation-menu.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/navigation-menu.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "popover": {
      name: "popover",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/popover.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/popover.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "progress": {
      name: "progress",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/progress.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/progress.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "radio-group": {
      name: "radio-group",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/radio-group.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/radio-group.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "resizable": {
      name: "resizable",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/resizable.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/resizable.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "scroll-area": {
      name: "scroll-area",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/scroll-area.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/scroll-area.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "select": {
      name: "select",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/select.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/select.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "skeleton": {
      name: "skeleton",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/skeleton.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/skeleton.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "slider": {
      name: "slider",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/slider.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/slider.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "sonner": {
      name: "sonner",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/sonner.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/sonner.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "spinner": {
      name: "spinner",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/spinner.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/spinner.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "switch": {
      name: "switch",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/switch.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/switch.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "table": {
      name: "table",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/table.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/table.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "tabs": {
      name: "tabs",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/tabs.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/tabs.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "textarea": {
      name: "textarea",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/textarea.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/textarea.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "toggle": {
      name: "toggle",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/toggle.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/toggle.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "toggle-group": {
      name: "toggle-group",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/ui/toggle-group.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/ui/toggle-group.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "login-01": {
      name: "login-01",
      description: "A simple login form.",
      type: "registry:block",
      registryDependencies: ["button","card","input","label","field"],
      files: [{
        path: "src/registry/v1/blocks/login-01/index.tsx",
        type: "registry:page",
        target: "app/login/index.tsx"
      },{
        path: "src/registry/v1/blocks/login-01/components/login-form.tsx",
        type: "registry:component",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/blocks/login-01/index.tsx")),
      categories: ["authentication","login"],
      meta: undefined,
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/lib/utils.ts")),
      categories: undefined,
      meta: undefined,
    },
    "use-mobile": {
      name: "use-mobile",
      description: "",
      type: "registry:hook",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/v1/hooks/use-mobile.ts",
        type: "registry:hook",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/hooks/use-mobile.ts")),
      categories: undefined,
      meta: undefined,
    },
    "accordion-demo": {
      name: "accordion-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["accordion"],
      files: [{
        path: "src/registry/v1/examples/accordion-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/accordion-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "alert-dialog-demo": {
      name: "alert-dialog-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["alert-dialog"],
      files: [{
        path: "src/registry/v1/examples/alert-dialog-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/alert-dialog-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "alert-demo": {
      name: "alert-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["alert"],
      files: [{
        path: "src/registry/v1/examples/alert-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/alert-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "aspect-ratio-demo": {
      name: "aspect-ratio-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["aspect-ratio"],
      files: [{
        path: "src/registry/v1/examples/aspect-ratio-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/aspect-ratio-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "avatar-demo": {
      name: "avatar-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["avatar"],
      files: [{
        path: "src/registry/v1/examples/avatar-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/avatar-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "badge-demo": {
      name: "badge-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["badge"],
      files: [{
        path: "src/registry/v1/examples/badge-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/badge-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "breadcrumb-demo": {
      name: "breadcrumb-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["breadcrumb","dropdown-menu"],
      files: [{
        path: "src/registry/v1/examples/breadcrumb-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/breadcrumb-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "button-group-demo": {
      name: "button-group-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button","button-group","dropdown-menu"],
      files: [{
        path: "src/registry/v1/examples/button-group-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/button-group-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "button-group-orientation": {
      name: "button-group-orientation",
      description: "",
      type: "registry:example",
      registryDependencies: ["button","button-group"],
      files: [{
        path: "src/registry/v1/examples/button-group-orientation.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/button-group-orientation.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "button-group-size": {
      name: "button-group-size",
      description: "",
      type: "registry:example",
      registryDependencies: ["button","button-group"],
      files: [{
        path: "src/registry/v1/examples/button-group-size.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/button-group-size.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "button-group-nested": {
      name: "button-group-nested",
      description: "",
      type: "registry:example",
      registryDependencies: ["button","button-group"],
      files: [{
        path: "src/registry/v1/examples/button-group-nested.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/button-group-nested.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "button-group-separator": {
      name: "button-group-separator",
      description: "",
      type: "registry:example",
      registryDependencies: ["button","button-group"],
      files: [{
        path: "src/registry/v1/examples/button-group-separator.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/button-group-separator.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "button-group-split": {
      name: "button-group-split",
      description: "",
      type: "registry:example",
      registryDependencies: ["button","button-group"],
      files: [{
        path: "src/registry/v1/examples/button-group-split.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/button-group-split.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "button-group-input": {
      name: "button-group-input",
      description: "",
      type: "registry:example",
      registryDependencies: ["button","button-group","input"],
      files: [{
        path: "src/registry/v1/examples/button-group-input.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/button-group-input.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "button-group-input-group": {
      name: "button-group-input-group",
      description: "",
      type: "registry:example",
      registryDependencies: ["button","button-group","input-group","tooltip"],
      files: [{
        path: "src/registry/v1/examples/button-group-input-group.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/button-group-input-group.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "button-group-dropdown-menu": {
      name: "button-group-dropdown-menu",
      description: "",
      type: "registry:example",
      registryDependencies: ["button","button-group","dropdown-menu"],
      files: [{
        path: "src/registry/v1/examples/button-group-dropdown-menu.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/button-group-dropdown-menu.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "button-group-select": {
      name: "button-group-select",
      description: "",
      type: "registry:example",
      registryDependencies: ["button","button-group","select","input"],
      files: [{
        path: "src/registry/v1/examples/button-group-select.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/button-group-select.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "button-group-popover": {
      name: "button-group-popover",
      description: "",
      type: "registry:example",
      registryDependencies: ["button","button-group","popover","separator","textarea"],
      files: [{
        path: "src/registry/v1/examples/button-group-popover.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/button-group-popover.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "button-demo": {
      name: "button-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "src/registry/v1/examples/button-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/button-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "button-default": {
      name: "button-default",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "src/registry/v1/examples/button-default.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/button-default.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "button-destructive": {
      name: "button-destructive",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "src/registry/v1/examples/button-destructive.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/button-destructive.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "button-ghost": {
      name: "button-ghost",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "src/registry/v1/examples/button-ghost.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/button-ghost.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "button-icon": {
      name: "button-icon",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "src/registry/v1/examples/button-icon.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/button-icon.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "button-link": {
      name: "button-link",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "src/registry/v1/examples/button-link.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/button-link.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "button-loading": {
      name: "button-loading",
      description: "",
      type: "registry:example",
      registryDependencies: ["button","spinner"],
      files: [{
        path: "src/registry/v1/examples/button-loading.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/button-loading.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "button-outline": {
      name: "button-outline",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "src/registry/v1/examples/button-outline.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/button-outline.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "button-rounded": {
      name: "button-rounded",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "src/registry/v1/examples/button-rounded.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/button-rounded.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "button-secondary": {
      name: "button-secondary",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "src/registry/v1/examples/button-secondary.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/button-secondary.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "button-sizes": {
      name: "button-sizes",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "src/registry/v1/examples/button-sizes.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/button-sizes.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "button-with-icon": {
      name: "button-with-icon",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "src/registry/v1/examples/button-with-icon.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/button-with-icon.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "calendar-demo": {
      name: "calendar-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["calendar"],
      files: [{
        path: "src/registry/v1/examples/calendar-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/calendar-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "card-demo": {
      name: "card-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["card","button","input","label"],
      files: [{
        path: "src/registry/v1/examples/card-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/card-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "carousel-demo": {
      name: "carousel-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["carousel","card"],
      files: [{
        path: "src/registry/v1/examples/carousel-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/carousel-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "collapsible-demo": {
      name: "collapsible-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["collapsible","button"],
      files: [{
        path: "src/registry/v1/examples/collapsible-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/collapsible-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "combobox-demo": {
      name: "combobox-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["combobox"],
      files: [{
        path: "src/registry/v1/examples/combobox-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/combobox-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "command-demo": {
      name: "command-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["command"],
      files: [{
        path: "src/registry/v1/examples/command-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/command-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "context-menu-demo": {
      name: "context-menu-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["context-menu"],
      files: [{
        path: "src/registry/v1/examples/context-menu-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/context-menu-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "data-table-demo": {
      name: "data-table-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button","checkbox","dropdown-menu","input","table"],
      files: [{
        path: "src/registry/v1/examples/data-table-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/data-table-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "date-picker-demo": {
      name: "date-picker-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["label","button","calendar","popover"],
      files: [{
        path: "src/registry/v1/examples/date-picker-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/date-picker-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "dialog-demo": {
      name: "dialog-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["dialog","button","input","label"],
      files: [{
        path: "src/registry/v1/examples/dialog-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/dialog-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "drawer-demo": {
      name: "drawer-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["drawer","button"],
      files: [{
        path: "src/registry/v1/examples/drawer-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/drawer-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "dropdown-menu-checkboxes": {
      name: "dropdown-menu-checkboxes",
      description: "",
      type: "registry:example",
      registryDependencies: ["dropdown-menu"],
      files: [{
        path: "src/registry/v1/examples/dropdown-menu-checkboxes.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/dropdown-menu-checkboxes.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "checkbox-demo": {
      name: "checkbox-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["checkbox"],
      files: [{
        path: "src/registry/v1/examples/checkbox-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/checkbox-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "dropdown-menu-demo": {
      name: "dropdown-menu-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["dropdown-menu"],
      files: [{
        path: "src/registry/v1/examples/dropdown-menu-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/dropdown-menu-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "dropdown-menu-dialog": {
      name: "dropdown-menu-dialog",
      description: "",
      type: "registry:example",
      registryDependencies: ["dropdown-menu"],
      files: [{
        path: "src/registry/v1/examples/dropdown-menu-dialog.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/dropdown-menu-dialog.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "dropdown-menu-radio-group": {
      name: "dropdown-menu-radio-group",
      description: "",
      type: "registry:example",
      registryDependencies: ["dropdown-menu"],
      files: [{
        path: "src/registry/v1/examples/dropdown-menu-radio-group.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/dropdown-menu-radio-group.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "empty-demo": {
      name: "empty-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["empty","button"],
      files: [{
        path: "src/registry/v1/examples/empty-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/empty-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "field-checkbox": {
      name: "field-checkbox",
      description: "",
      type: "registry:example",
      registryDependencies: ["field","checkbox"],
      files: [{
        path: "src/registry/v1/examples/field-checkbox.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/field-checkbox.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "field-choice-card": {
      name: "field-choice-card",
      description: "",
      type: "registry:example",
      registryDependencies: ["field","radio-group"],
      files: [{
        path: "src/registry/v1/examples/field-choice-card.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/field-choice-card.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "field-demo": {
      name: "field-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["field"],
      files: [{
        path: "src/registry/v1/examples/field-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/field-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "field-fieldset": {
      name: "field-fieldset",
      description: "",
      type: "registry:example",
      registryDependencies: ["field","input"],
      files: [{
        path: "src/registry/v1/examples/field-fieldset.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/field-fieldset.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "field-group-example": {
      name: "field-group-example",
      description: "",
      type: "registry:example",
      registryDependencies: ["field","checkbox"],
      files: [{
        path: "src/registry/v1/examples/field-group-example.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/field-group-example.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "field-input": {
      name: "field-input",
      description: "",
      type: "registry:example",
      registryDependencies: ["field","input"],
      files: [{
        path: "src/registry/v1/examples/field-input.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/field-input.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "field-radio": {
      name: "field-radio",
      description: "",
      type: "registry:example",
      registryDependencies: ["field","radio-group"],
      files: [{
        path: "src/registry/v1/examples/field-radio.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/field-radio.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "field-responsive": {
      name: "field-responsive",
      description: "",
      type: "registry:example",
      registryDependencies: ["field","button","input","textarea"],
      files: [{
        path: "src/registry/v1/examples/field-responsive.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/field-responsive.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "field-select": {
      name: "field-select",
      description: "",
      type: "registry:example",
      registryDependencies: ["field","select"],
      files: [{
        path: "src/registry/v1/examples/field-select.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/field-select.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "field-slider": {
      name: "field-slider",
      description: "",
      type: "registry:example",
      registryDependencies: ["field","slider"],
      files: [{
        path: "src/registry/v1/examples/field-slider.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/field-slider.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "field-switch": {
      name: "field-switch",
      description: "",
      type: "registry:example",
      registryDependencies: ["field","switch"],
      files: [{
        path: "src/registry/v1/examples/field-switch.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/field-switch.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "field-textarea": {
      name: "field-textarea",
      description: "",
      type: "registry:example",
      registryDependencies: ["field","textarea"],
      files: [{
        path: "src/registry/v1/examples/field-textarea.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/field-textarea.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "hover-card-demo": {
      name: "hover-card-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["hover-card","button","avatar"],
      files: [{
        path: "src/registry/v1/examples/hover-card-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/hover-card-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "input-group-demo": {
      name: "input-group-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["input-group"],
      files: [{
        path: "src/registry/v1/examples/input-group-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/input-group-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "input-otp-demo": {
      name: "input-otp-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["input-otp"],
      files: [{
        path: "src/registry/v1/examples/input-otp-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/input-otp-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "input-demo": {
      name: "input-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["input"],
      files: [{
        path: "src/registry/v1/examples/input-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/input-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "item-demo": {
      name: "item-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["item","button"],
      files: [{
        path: "src/registry/v1/examples/item-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/item-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "kbd-demo": {
      name: "kbd-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["kbd"],
      files: [{
        path: "src/registry/v1/examples/kbd-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/kbd-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "label-demo": {
      name: "label-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["label","checkbox"],
      files: [{
        path: "src/registry/v1/examples/label-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/label-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "menubar-demo": {
      name: "menubar-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["menubar"],
      files: [{
        path: "src/registry/v1/examples/menubar-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/menubar-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "native-select-demo": {
      name: "native-select-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["native-select"],
      files: [{
        path: "src/registry/v1/examples/native-select-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/native-select-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "navigation-menu-demo": {
      name: "navigation-menu-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["navigation-menu"],
      files: [{
        path: "src/registry/v1/examples/navigation-menu-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/navigation-menu-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "popover-demo": {
      name: "popover-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["popover","button","input","label"],
      files: [{
        path: "src/registry/v1/examples/popover-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/popover-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "progress-demo": {
      name: "progress-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["progress"],
      files: [{
        path: "src/registry/v1/examples/progress-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/progress-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "radio-group-demo": {
      name: "radio-group-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["radio-group","label"],
      files: [{
        path: "src/registry/v1/examples/radio-group-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/radio-group-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "resizable-demo": {
      name: "resizable-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["resizable"],
      files: [{
        path: "src/registry/v1/examples/resizable-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/resizable-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "scroll-area-demo": {
      name: "scroll-area-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["scroll-area","separator"],
      files: [{
        path: "src/registry/v1/examples/scroll-area-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/scroll-area-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "select-demo": {
      name: "select-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["select"],
      files: [{
        path: "src/registry/v1/examples/select-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/select-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "separator-demo": {
      name: "separator-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["separator"],
      files: [{
        path: "src/registry/v1/examples/separator-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/separator-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "sheet-demo": {
      name: "sheet-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["sheet","button","input","label"],
      files: [{
        path: "src/registry/v1/examples/sheet-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/sheet-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "skeleton-demo": {
      name: "skeleton-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["skeleton"],
      files: [{
        path: "src/registry/v1/examples/skeleton-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/skeleton-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "skeleton-card": {
      name: "skeleton-card",
      description: "",
      type: "registry:example",
      registryDependencies: ["skeleton"],
      files: [{
        path: "src/registry/v1/examples/skeleton-card.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/skeleton-card.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "slider-demo": {
      name: "slider-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["slider"],
      files: [{
        path: "src/registry/v1/examples/slider-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/slider-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "sonner-demo": {
      name: "sonner-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["sonner","button"],
      files: [{
        path: "src/registry/v1/examples/sonner-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/sonner-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "sonner-types": {
      name: "sonner-types",
      description: "",
      type: "registry:example",
      registryDependencies: ["sonner","button"],
      files: [{
        path: "src/registry/v1/examples/sonner-types.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/sonner-types.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "spinner-demo": {
      name: "spinner-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["spinner","item"],
      files: [{
        path: "src/registry/v1/examples/spinner-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/spinner-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "switch-demo": {
      name: "switch-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["switch","label"],
      files: [{
        path: "src/registry/v1/examples/switch-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/switch-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "table-demo": {
      name: "table-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["table"],
      files: [{
        path: "src/registry/v1/examples/table-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/table-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "tabs-demo": {
      name: "tabs-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["tabs","card","input","label"],
      files: [{
        path: "src/registry/v1/examples/tabs-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/tabs-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "textarea-demo": {
      name: "textarea-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["textarea"],
      files: [{
        path: "src/registry/v1/examples/textarea-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/textarea-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "toggle-group-demo": {
      name: "toggle-group-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle-group"],
      files: [{
        path: "src/registry/v1/examples/toggle-group-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/toggle-group-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "toggle-demo": {
      name: "toggle-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle"],
      files: [{
        path: "src/registry/v1/examples/toggle-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/toggle-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
    "tooltip-demo": {
      name: "tooltip-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["tooltip"],
      files: [{
        path: "src/registry/v1/examples/tooltip-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: lazy(() => import("~/registry/v1/examples/tooltip-demo.tsx")),
      categories: undefined,
      meta: undefined,
    },
  },
}