// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import { lazy } from "solid-js"

export const Index: Record<string, any> = {
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/lib/utils.ts")),
    files: [{
      path: "registry/lib/utils.ts",
      type: "registry:lib",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "accordion": {
    name: "accordion",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/accordion.tsx")),
    files: [{
      path: "registry/ui/accordion.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "alert": {
    name: "alert",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/alert.tsx")),
    files: [{
      path: "registry/ui/alert.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "alert-dialog": {
    name: "alert-dialog",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/ui/alert-dialog.tsx")),
    files: [{
      path: "registry/ui/alert-dialog.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "aspect-ratio": {
    name: "aspect-ratio",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/aspect-ratio.tsx")),
    files: [{
      path: "registry/ui/aspect-ratio.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "avatar": {
    name: "avatar",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/avatar.tsx")),
    files: [{
      path: "registry/ui/avatar.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "badge": {
    name: "badge",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/badge.tsx")),
    files: [{
      path: "registry/ui/badge.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "breadcrumb": {
    name: "breadcrumb",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/breadcrumb.tsx")),
    files: [{
      path: "registry/ui/breadcrumb.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button": {
    name: "button",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/button.tsx")),
    files: [{
      path: "registry/ui/button.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "card": {
    name: "card",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/card.tsx")),
    files: [{
      path: "registry/ui/card.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-group": {
    name: "button-group",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button","separator"],
    component: lazy(() => import("~/registry/ui/button-group.tsx")),
    files: [{
      path: "registry/ui/button-group.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "carousel": {
    name: "carousel",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/ui/carousel.tsx")),
    files: [{
      path: "registry/ui/carousel.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "chart": {
    name: "chart",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/chart.tsx")),
    files: [{
      path: "registry/ui/chart.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "checkbox": {
    name: "checkbox",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/checkbox.tsx")),
    files: [{
      path: "registry/ui/checkbox.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "collapsible": {
    name: "collapsible",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/collapsible.tsx")),
    files: [{
      path: "registry/ui/collapsible.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "combobox": {
    name: "combobox",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/combobox.tsx")),
    files: [{
      path: "registry/ui/combobox.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "command": {
    name: "command",
    description: "",
    type: "registry:ui",
    registryDependencies: ["dialog"],
    component: lazy(() => import("~/registry/ui/command.tsx")),
    files: [{
      path: "registry/ui/command.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "context-menu": {
    name: "context-menu",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/context-menu.tsx")),
    files: [{
      path: "registry/ui/context-menu.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "dialog": {
    name: "dialog",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/dialog.tsx")),
    files: [{
      path: "registry/ui/dialog.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "direction": {
    name: "direction",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/direction.tsx")),
    files: [{
      path: "registry/ui/direction.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "dropdown-menu": {
    name: "dropdown-menu",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/dropdown-menu.tsx")),
    files: [{
      path: "registry/ui/dropdown-menu.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "empty": {
    name: "empty",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/empty.tsx")),
    files: [{
      path: "registry/ui/empty.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "field": {
    name: "field",
    description: "",
    type: "registry:ui",
    registryDependencies: ["label","separator"],
    component: lazy(() => import("~/registry/ui/field.tsx")),
    files: [{
      path: "registry/ui/field.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "form": {
    name: "form",
    description: "",
    type: "registry:ui",
    registryDependencies: ["label"],
    component: lazy(() => import("~/registry/ui/form.tsx")),
    files: [{
      path: "registry/ui/form.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "hover-card": {
    name: "hover-card",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/hover-card.tsx")),
    files: [{
      path: "registry/ui/hover-card.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input": {
    name: "input",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/input.tsx")),
    files: [{
      path: "registry/ui/input.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-group": {
    name: "input-group",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button","input","textarea"],
    component: lazy(() => import("~/registry/ui/input-group.tsx")),
    files: [{
      path: "registry/ui/input-group.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-otp": {
    name: "input-otp",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/input-otp.tsx")),
    files: [{
      path: "registry/ui/input-otp.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "item": {
    name: "item",
    description: "",
    type: "registry:ui",
    registryDependencies: ["separator"],
    component: lazy(() => import("~/registry/ui/item.tsx")),
    files: [{
      path: "registry/ui/item.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "kbd": {
    name: "kbd",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/kbd.tsx")),
    files: [{
      path: "registry/ui/kbd.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "label": {
    name: "label",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/label.tsx")),
    files: [{
      path: "registry/ui/label.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "menubar": {
    name: "menubar",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/menubar.tsx")),
    files: [{
      path: "registry/ui/menubar.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "navigation-menu": {
    name: "navigation-menu",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/navigation-menu.tsx")),
    files: [{
      path: "registry/ui/navigation-menu.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "native-select": {
    name: "native-select",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/native-select.tsx")),
    files: [{
      path: "registry/ui/native-select.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "pagination": {
    name: "pagination",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/ui/pagination.tsx")),
    files: [{
      path: "registry/ui/pagination.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "popover": {
    name: "popover",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/popover.tsx")),
    files: [{
      path: "registry/ui/popover.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "progress": {
    name: "progress",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/progress.tsx")),
    files: [{
      path: "registry/ui/progress.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "radio-group": {
    name: "radio-group",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/radio-group.tsx")),
    files: [{
      path: "registry/ui/radio-group.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "resizable": {
    name: "resizable",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/resizable.tsx")),
    files: [{
      path: "registry/ui/resizable.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "scroll-area": {
    name: "scroll-area",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/scroll-area.tsx")),
    files: [{
      path: "registry/ui/scroll-area.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "select": {
    name: "select",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/select.tsx")),
    files: [{
      path: "registry/ui/select.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "slider": {
    name: "slider",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/slider.tsx")),
    files: [{
      path: "registry/ui/slider.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "sonner": {
    name: "sonner",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/sonner.tsx")),
    files: [{
      path: "registry/ui/sonner.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "switch": {
    name: "switch",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/switch.tsx")),
    files: [{
      path: "registry/ui/switch.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "tabs": {
    name: "tabs",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/tabs.tsx")),
    files: [{
      path: "registry/ui/tabs.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "textarea": {
    name: "textarea",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/textarea.tsx")),
    files: [{
      path: "registry/ui/textarea.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "toggle": {
    name: "toggle",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/toggle.tsx")),
    files: [{
      path: "registry/ui/toggle.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "toggle-group": {
    name: "toggle-group",
    description: "",
    type: "registry:ui",
    registryDependencies: ["toggle"],
    component: lazy(() => import("~/registry/ui/toggle-group.tsx")),
    files: [{
      path: "registry/ui/toggle-group.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "tooltip": {
    name: "tooltip",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/tooltip.tsx")),
    files: [{
      path: "registry/ui/tooltip.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "use-mobile": {
    name: "use-mobile",
    description: "",
    type: "registry:hook",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/hooks/use-mobile.ts")),
    files: [{
      path: "registry/hooks/use-mobile.ts",
      type: "registry:hook",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "accordion-demo": {
    name: "accordion-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["accordion"],
    component: lazy(() => import("~/registry/examples/accordion-demo.tsx")),
    files: [{
      path: "registry/examples/accordion-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "alert-demo": {
    name: "alert-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["alert"],
    component: lazy(() => import("~/registry/examples/alert-demo.tsx")),
    files: [{
      path: "registry/examples/alert-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "alert-dialog-demo": {
    name: "alert-dialog-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["alert-dialog","button"],
    component: lazy(() => import("~/registry/examples/alert-dialog-demo.tsx")),
    files: [{
      path: "registry/examples/alert-dialog-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "aspect-ratio-demo": {
    name: "aspect-ratio-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["aspect-ratio"],
    component: lazy(() => import("~/registry/examples/aspect-ratio-demo.tsx")),
    files: [{
      path: "registry/examples/aspect-ratio-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "avatar-demo": {
    name: "avatar-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["avatar"],
    component: lazy(() => import("~/registry/examples/avatar-demo.tsx")),
    files: [{
      path: "registry/examples/avatar-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "badge-demo": {
    name: "badge-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["badge"],
    component: lazy(() => import("~/registry/examples/badge-demo.tsx")),
    files: [{
      path: "registry/examples/badge-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "breadcrumb-collapsed": {
    name: "breadcrumb-collapsed",
    description: "",
    type: "registry:example",
    registryDependencies: ["breadcrumb"],
    component: lazy(() => import("~/registry/examples/breadcrumb-collapsed.tsx")),
    files: [{
      path: "registry/examples/breadcrumb-collapsed.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "breadcrumb-demo": {
    name: "breadcrumb-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["breadcrumb"],
    component: lazy(() => import("~/registry/examples/breadcrumb-demo.tsx")),
    files: [{
      path: "registry/examples/breadcrumb-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "breadcrumb-dropdown": {
    name: "breadcrumb-dropdown",
    description: "",
    type: "registry:example",
    registryDependencies: ["breadcrumb","dropdown-menu","button"],
    component: lazy(() => import("~/registry/examples/breadcrumb-dropdown.tsx")),
    files: [{
      path: "registry/examples/breadcrumb-dropdown.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "breadcrumb-link": {
    name: "breadcrumb-link",
    description: "",
    type: "registry:example",
    registryDependencies: ["breadcrumb"],
    component: lazy(() => import("~/registry/examples/breadcrumb-link.tsx")),
    files: [{
      path: "registry/examples/breadcrumb-link.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "breadcrumb-separator": {
    name: "breadcrumb-separator",
    description: "",
    type: "registry:example",
    registryDependencies: ["breadcrumb"],
    component: lazy(() => import("~/registry/examples/breadcrumb-separator.tsx")),
    files: [{
      path: "registry/examples/breadcrumb-separator.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-default": {
    name: "button-default",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/examples/button-default.tsx")),
    files: [{
      path: "registry/examples/button-default.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-demo": {
    name: "button-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/examples/button-demo.tsx")),
    files: [{
      path: "registry/examples/button-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-destructive": {
    name: "button-destructive",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/examples/button-destructive.tsx")),
    files: [{
      path: "registry/examples/button-destructive.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-ghost": {
    name: "button-ghost",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/examples/button-ghost.tsx")),
    files: [{
      path: "registry/examples/button-ghost.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-group-demo": {
    name: "button-group-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["button","button-group","dropdown-menu"],
    component: lazy(() => import("~/registry/examples/button-group-demo.tsx")),
    files: [{
      path: "registry/examples/button-group-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-group-dropdown-menu": {
    name: "button-group-dropdown-menu",
    description: "",
    type: "registry:example",
    registryDependencies: ["button","button-group","dropdown-menu"],
    component: lazy(() => import("~/registry/examples/button-group-dropdown-menu.tsx")),
    files: [{
      path: "registry/examples/button-group-dropdown-menu.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-group-input": {
    name: "button-group-input",
    description: "",
    type: "registry:example",
    registryDependencies: ["button","button-group","input"],
    component: lazy(() => import("~/registry/examples/button-group-input.tsx")),
    files: [{
      path: "registry/examples/button-group-input.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-group-input-group": {
    name: "button-group-input-group",
    description: "",
    type: "registry:example",
    registryDependencies: ["button","button-group","input-group"],
    component: lazy(() => import("~/registry/examples/button-group-input-group.tsx")),
    files: [{
      path: "registry/examples/button-group-input-group.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-group-nested": {
    name: "button-group-nested",
    description: "",
    type: "registry:example",
    registryDependencies: ["button","button-group"],
    component: lazy(() => import("~/registry/examples/button-group-nested.tsx")),
    files: [{
      path: "registry/examples/button-group-nested.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-group-orientation": {
    name: "button-group-orientation",
    description: "",
    type: "registry:example",
    registryDependencies: ["button","button-group"],
    component: lazy(() => import("~/registry/examples/button-group-orientation.tsx")),
    files: [{
      path: "registry/examples/button-group-orientation.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-group-select": {
    name: "button-group-select",
    description: "",
    type: "registry:example",
    registryDependencies: ["button","button-group","select"],
    component: lazy(() => import("~/registry/examples/button-group-select.tsx")),
    files: [{
      path: "registry/examples/button-group-select.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-group-separator": {
    name: "button-group-separator",
    description: "",
    type: "registry:example",
    registryDependencies: ["button","button-group"],
    component: lazy(() => import("~/registry/examples/button-group-separator.tsx")),
    files: [{
      path: "registry/examples/button-group-separator.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-group-size": {
    name: "button-group-size",
    description: "",
    type: "registry:example",
    registryDependencies: ["button","button-group"],
    component: lazy(() => import("~/registry/examples/button-group-size.tsx")),
    files: [{
      path: "registry/examples/button-group-size.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-group-split": {
    name: "button-group-split",
    description: "",
    type: "registry:example",
    registryDependencies: ["button","button-group"],
    component: lazy(() => import("~/registry/examples/button-group-split.tsx")),
    files: [{
      path: "registry/examples/button-group-split.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-icon": {
    name: "button-icon",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/examples/button-icon.tsx")),
    files: [{
      path: "registry/examples/button-icon.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-link": {
    name: "button-link",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/examples/button-link.tsx")),
    files: [{
      path: "registry/examples/button-link.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-loading": {
    name: "button-loading",
    description: "",
    type: "registry:example",
    registryDependencies: ["button","spinner"],
    component: lazy(() => import("~/registry/examples/button-loading.tsx")),
    files: [{
      path: "registry/examples/button-loading.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-outline": {
    name: "button-outline",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/examples/button-outline.tsx")),
    files: [{
      path: "registry/examples/button-outline.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-rounded": {
    name: "button-rounded",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/examples/button-rounded.tsx")),
    files: [{
      path: "registry/examples/button-rounded.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-secondary": {
    name: "button-secondary",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/examples/button-secondary.tsx")),
    files: [{
      path: "registry/examples/button-secondary.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-sizes": {
    name: "button-sizes",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/examples/button-sizes.tsx")),
    files: [{
      path: "registry/examples/button-sizes.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-with-icon": {
    name: "button-with-icon",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/examples/button-with-icon.tsx")),
    files: [{
      path: "registry/examples/button-with-icon.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "card-demo": {
    name: "card-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["card","button","input","label"],
    component: lazy(() => import("~/registry/examples/card-demo.tsx")),
    files: [{
      path: "registry/examples/card-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "carousel-api": {
    name: "carousel-api",
    description: "",
    type: "registry:example",
    registryDependencies: ["carousel","card"],
    component: lazy(() => import("~/registry/examples/carousel-api.tsx")),
    files: [{
      path: "registry/examples/carousel-api.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "carousel-demo": {
    name: "carousel-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["carousel","card"],
    component: lazy(() => import("~/registry/examples/carousel-demo.tsx")),
    files: [{
      path: "registry/examples/carousel-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "carousel-orientation": {
    name: "carousel-orientation",
    description: "",
    type: "registry:example",
    registryDependencies: ["carousel","card"],
    component: lazy(() => import("~/registry/examples/carousel-orientation.tsx")),
    files: [{
      path: "registry/examples/carousel-orientation.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "carousel-plugin": {
    name: "carousel-plugin",
    description: "",
    type: "registry:example",
    registryDependencies: ["carousel","card"],
    component: lazy(() => import("~/registry/examples/carousel-plugin.tsx")),
    files: [{
      path: "registry/examples/carousel-plugin.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "carousel-size": {
    name: "carousel-size",
    description: "",
    type: "registry:example",
    registryDependencies: ["carousel","card"],
    component: lazy(() => import("~/registry/examples/carousel-size.tsx")),
    files: [{
      path: "registry/examples/carousel-size.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "carousel-spacing": {
    name: "carousel-spacing",
    description: "",
    type: "registry:example",
    registryDependencies: ["carousel","card"],
    component: lazy(() => import("~/registry/examples/carousel-spacing.tsx")),
    files: [{
      path: "registry/examples/carousel-spacing.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "chart-demo": {
    name: "chart-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["chart","card"],
    component: lazy(() => import("~/registry/examples/chart-demo.tsx")),
    files: [{
      path: "registry/examples/chart-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "checkbox-demo": {
    name: "checkbox-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["checkbox"],
    component: lazy(() => import("~/registry/examples/checkbox-demo.tsx")),
    files: [{
      path: "registry/examples/checkbox-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "collapsible-demo": {
    name: "collapsible-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["collapsible","button"],
    component: lazy(() => import("~/registry/examples/collapsible-demo.tsx")),
    files: [{
      path: "registry/examples/collapsible-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "combobox-demo": {
    name: "combobox-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["combobox"],
    component: lazy(() => import("~/registry/examples/combobox-demo.tsx")),
    files: [{
      path: "registry/examples/combobox-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "command-demo": {
    name: "command-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["command"],
    component: lazy(() => import("~/registry/examples/command-demo.tsx")),
    files: [{
      path: "registry/examples/command-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "command-dialog": {
    name: "command-dialog",
    description: "",
    type: "registry:example",
    registryDependencies: ["command","button"],
    component: lazy(() => import("~/registry/examples/command-dialog.tsx")),
    files: [{
      path: "registry/examples/command-dialog.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "dialog-close-button": {
    name: "dialog-close-button",
    description: "",
    type: "registry:example",
    registryDependencies: ["dialog","button"],
    component: lazy(() => import("~/registry/examples/dialog-close-button.tsx")),
    files: [{
      path: "registry/examples/dialog-close-button.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "dialog-demo": {
    name: "dialog-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["dialog","button","field","input"],
    component: lazy(() => import("~/registry/examples/dialog-demo.tsx")),
    files: [{
      path: "registry/examples/dialog-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "direction-demo": {
    name: "direction-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["direction"],
    component: lazy(() => import("~/registry/examples/direction-demo.tsx")),
    files: [{
      path: "registry/examples/direction-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "context-menu-checkboxes": {
    name: "context-menu-checkboxes",
    description: "",
    type: "registry:example",
    registryDependencies: ["context-menu"],
    component: lazy(() => import("~/registry/examples/context-menu-checkboxes.tsx")),
    files: [{
      path: "registry/examples/context-menu-checkboxes.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "context-menu-demo": {
    name: "context-menu-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["context-menu"],
    component: lazy(() => import("~/registry/examples/context-menu-demo.tsx")),
    files: [{
      path: "registry/examples/context-menu-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "context-menu-radio-group": {
    name: "context-menu-radio-group",
    description: "",
    type: "registry:example",
    registryDependencies: ["context-menu"],
    component: lazy(() => import("~/registry/examples/context-menu-radio-group.tsx")),
    files: [{
      path: "registry/examples/context-menu-radio-group.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "dropdown-menu-checkboxes": {
    name: "dropdown-menu-checkboxes",
    description: "",
    type: "registry:example",
    registryDependencies: ["dropdown-menu"],
    component: lazy(() => import("~/registry/examples/dropdown-menu-checkboxes.tsx")),
    files: [{
      path: "registry/examples/dropdown-menu-checkboxes.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "dropdown-menu-demo": {
    name: "dropdown-menu-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["dropdown-menu"],
    component: lazy(() => import("~/registry/examples/dropdown-menu-demo.tsx")),
    files: [{
      path: "registry/examples/dropdown-menu-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "dropdown-menu-dialog": {
    name: "dropdown-menu-dialog",
    description: "",
    type: "registry:example",
    registryDependencies: ["dropdown-menu"],
    component: lazy(() => import("~/registry/examples/dropdown-menu-dialog.tsx")),
    files: [{
      path: "registry/examples/dropdown-menu-dialog.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "dropdown-menu-radio-group": {
    name: "dropdown-menu-radio-group",
    description: "",
    type: "registry:example",
    registryDependencies: ["dropdown-menu"],
    component: lazy(() => import("~/registry/examples/dropdown-menu-radio-group.tsx")),
    files: [{
      path: "registry/examples/dropdown-menu-radio-group.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "empty-demo": {
    name: "empty-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["empty","button"],
    component: lazy(() => import("~/registry/examples/empty-demo.tsx")),
    files: [{
      path: "registry/examples/empty-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "field-checkbox": {
    name: "field-checkbox",
    description: "",
    type: "registry:example",
    registryDependencies: ["field","checkbox"],
    component: lazy(() => import("~/registry/examples/field-checkbox.tsx")),
    files: [{
      path: "registry/examples/field-checkbox.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "field-choice-card": {
    name: "field-choice-card",
    description: "",
    type: "registry:example",
    registryDependencies: ["field","radio-group"],
    component: lazy(() => import("~/registry/examples/field-choice-card.tsx")),
    files: [{
      path: "registry/examples/field-choice-card.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "field-demo": {
    name: "field-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["field"],
    component: lazy(() => import("~/registry/examples/field-demo.tsx")),
    files: [{
      path: "registry/examples/field-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "field-fieldset": {
    name: "field-fieldset",
    description: "",
    type: "registry:example",
    registryDependencies: ["field","input"],
    component: lazy(() => import("~/registry/examples/field-fieldset.tsx")),
    files: [{
      path: "registry/examples/field-fieldset.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "field-group-example": {
    name: "field-group-example",
    description: "",
    type: "registry:example",
    registryDependencies: ["field","checkbox"],
    component: lazy(() => import("~/registry/examples/field-group-example.tsx")),
    files: [{
      path: "registry/examples/field-group-example.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "field-input": {
    name: "field-input",
    description: "",
    type: "registry:example",
    registryDependencies: ["field","input"],
    component: lazy(() => import("~/registry/examples/field-input.tsx")),
    files: [{
      path: "registry/examples/field-input.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "field-radio": {
    name: "field-radio",
    description: "",
    type: "registry:example",
    registryDependencies: ["field","radio-group"],
    component: lazy(() => import("~/registry/examples/field-radio.tsx")),
    files: [{
      path: "registry/examples/field-radio.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "field-responsive": {
    name: "field-responsive",
    description: "",
    type: "registry:example",
    registryDependencies: ["field","button","input","textarea"],
    component: lazy(() => import("~/registry/examples/field-responsive.tsx")),
    files: [{
      path: "registry/examples/field-responsive.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "field-select": {
    name: "field-select",
    description: "",
    type: "registry:example",
    registryDependencies: ["field","select"],
    component: lazy(() => import("~/registry/examples/field-select.tsx")),
    files: [{
      path: "registry/examples/field-select.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "field-slider": {
    name: "field-slider",
    description: "",
    type: "registry:example",
    registryDependencies: ["field","slider"],
    component: lazy(() => import("~/registry/examples/field-slider.tsx")),
    files: [{
      path: "registry/examples/field-slider.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "field-switch": {
    name: "field-switch",
    description: "",
    type: "registry:example",
    registryDependencies: ["field","switch"],
    component: lazy(() => import("~/registry/examples/field-switch.tsx")),
    files: [{
      path: "registry/examples/field-switch.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "field-textarea": {
    name: "field-textarea",
    description: "",
    type: "registry:example",
    registryDependencies: ["field","textarea"],
    component: lazy(() => import("~/registry/examples/field-textarea.tsx")),
    files: [{
      path: "registry/examples/field-textarea.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "form-demo": {
    name: "form-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["form","button","input","textarea"],
    component: lazy(() => import("~/registry/examples/form-demo.tsx")),
    files: [{
      path: "registry/examples/form-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "hover-card-demo": {
    name: "hover-card-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["hover-card","avatar","button"],
    component: lazy(() => import("~/registry/examples/hover-card-demo.tsx")),
    files: [{
      path: "registry/examples/hover-card-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-group-demo": {
    name: "input-group-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["input-group"],
    component: lazy(() => import("~/registry/examples/input-group-demo.tsx")),
    files: [{
      path: "registry/examples/input-group-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-otp-demo": {
    name: "input-otp-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["input-otp"],
    component: lazy(() => import("~/registry/examples/input-otp-demo.tsx")),
    files: [{
      path: "registry/examples/input-otp-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "item-demo": {
    name: "item-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["item","button"],
    component: lazy(() => import("~/registry/examples/item-demo.tsx")),
    files: [{
      path: "registry/examples/item-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "kbd-demo": {
    name: "kbd-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["kbd"],
    component: lazy(() => import("~/registry/examples/kbd-demo.tsx")),
    files: [{
      path: "registry/examples/kbd-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "label-demo": {
    name: "label-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["label","checkbox"],
    component: lazy(() => import("~/registry/examples/label-demo.tsx")),
    files: [{
      path: "registry/examples/label-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "menubar-demo": {
    name: "menubar-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["menubar"],
    component: lazy(() => import("~/registry/examples/menubar-demo.tsx")),
    files: [{
      path: "registry/examples/menubar-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "navigation-menu-demo": {
    name: "navigation-menu-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["navigation-menu"],
    component: lazy(() => import("~/registry/examples/navigation-menu-demo.tsx")),
    files: [{
      path: "registry/examples/navigation-menu-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "native-select-demo": {
    name: "native-select-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["native-select"],
    component: lazy(() => import("~/registry/examples/native-select-demo.tsx")),
    files: [{
      path: "registry/examples/native-select-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "pagination-demo": {
    name: "pagination-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["pagination"],
    component: lazy(() => import("~/registry/examples/pagination-demo.tsx")),
    files: [{
      path: "registry/examples/pagination-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "popover-demo": {
    name: "popover-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["popover","button","input","label"],
    component: lazy(() => import("~/registry/examples/popover-demo.tsx")),
    files: [{
      path: "registry/examples/popover-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "progress-demo": {
    name: "progress-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["progress"],
    component: lazy(() => import("~/registry/examples/progress-demo.tsx")),
    files: [{
      path: "registry/examples/progress-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "radio-group-demo": {
    name: "radio-group-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["radio-group","label"],
    component: lazy(() => import("~/registry/examples/radio-group-demo.tsx")),
    files: [{
      path: "registry/examples/radio-group-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "resizable-demo": {
    name: "resizable-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["resizable"],
    component: lazy(() => import("~/registry/examples/resizable-demo.tsx")),
    files: [{
      path: "registry/examples/resizable-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "scroll-area-demo": {
    name: "scroll-area-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["scroll-area","separator"],
    component: lazy(() => import("~/registry/examples/scroll-area-demo.tsx")),
    files: [{
      path: "registry/examples/scroll-area-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "select-demo": {
    name: "select-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["select"],
    component: lazy(() => import("~/registry/examples/select-demo.tsx")),
    files: [{
      path: "registry/examples/select-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "slider-demo": {
    name: "slider-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["slider"],
    component: lazy(() => import("~/registry/examples/slider-demo.tsx")),
    files: [{
      path: "registry/examples/slider-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "sonner-demo": {
    name: "sonner-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["sonner","button"],
    component: lazy(() => import("~/registry/examples/sonner-demo.tsx")),
    files: [{
      path: "registry/examples/sonner-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "switch-demo": {
    name: "switch-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["switch","label"],
    component: lazy(() => import("~/registry/examples/switch-demo.tsx")),
    files: [{
      path: "registry/examples/switch-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "toggle-demo": {
    name: "toggle-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["toggle"],
    component: lazy(() => import("~/registry/examples/toggle-demo.tsx")),
    files: [{
      path: "registry/examples/toggle-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "toggle-group-demo": {
    name: "toggle-group-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["toggle-group"],
    component: lazy(() => import("~/registry/examples/toggle-group-demo.tsx")),
    files: [{
      path: "registry/examples/toggle-group-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "tooltip-demo": {
    name: "tooltip-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["tooltip"],
    component: lazy(() => import("~/registry/examples/tooltip-demo.tsx")),
    files: [{
      path: "registry/examples/tooltip-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
}
