// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import { lazy } from "solid-js";

import type { RegistryIndex } from "~/registry/schema";

export const Index: RegistryIndex = {
  accordion: {
    component: lazy(() => import("~/registry/ui/accordion")),
    description: "",
    files: [
      {
        path: "registry/ui/accordion.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "accordion",
    registryDependencies: undefined,
    type: "ui",
  },
  "accordion-demo": {
    component: lazy(() => import("~/registry/example/accordion-demo")),
    description: "",
    files: [
      {
        path: "registry/example/accordion-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "accordion-demo",
    registryDependencies: undefined,
    type: "example",
  },
  alert: {
    component: lazy(() => import("~/registry/ui/alert")),
    description: "",
    files: [
      {
        path: "registry/ui/alert.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "alert",
    registryDependencies: undefined,
    type: "ui",
  },
  "alert-demo": {
    component: lazy(() => import("~/registry/example/alert-demo")),
    description: "",
    files: [
      {
        path: "registry/example/alert-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "alert-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "alert-dialog": {
    component: lazy(() => import("~/registry/ui/alert-dialog")),
    description: "",
    files: [
      {
        path: "registry/ui/alert-dialog.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "alert-dialog",
    registryDependencies: undefined,
    type: "ui",
  },
  "alert-dialog-demo": {
    component: lazy(() => import("~/registry/example/alert-dialog-demo")),
    description: "",
    files: [
      {
        path: "registry/example/alert-dialog-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "alert-dialog-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "area-chart-demo": {
    component: lazy(() => import("~/registry/example/area-chart-demo")),
    description: "",
    files: [
      {
        path: "registry/example/area-chart-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "area-chart-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "aspect-ratio": {
    component: lazy(() => import("~/registry/ui/aspect-ratio")),
    description: "",
    files: [
      {
        path: "registry/ui/aspect-ratio.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "aspect-ratio",
    registryDependencies: undefined,
    type: "ui",
  },
  "aspect-ratio-demo": {
    component: lazy(() => import("~/registry/example/aspect-ratio-demo")),
    description: "",
    files: [
      {
        path: "registry/example/aspect-ratio-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "aspect-ratio-demo",
    registryDependencies: undefined,
    type: "example",
  },
  avatar: {
    component: lazy(() => import("~/registry/ui/avatar")),
    description: "",
    files: [
      {
        path: "registry/ui/avatar.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "avatar",
    registryDependencies: undefined,
    type: "ui",
  },
  "avatar-demo": {
    component: lazy(() => import("~/registry/example/avatar-demo")),
    description: "",
    files: [
      {
        path: "registry/example/avatar-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "avatar-demo",
    registryDependencies: undefined,
    type: "example",
  },
  badge: {
    component: lazy(() => import("~/registry/ui/badge")),
    description: "",
    files: [
      {
        path: "registry/ui/badge.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "badge",
    registryDependencies: undefined,
    type: "ui",
  },
  "badge-delta": {
    component: lazy(() => import("~/registry/ui/badge-delta")),
    description: "",
    files: [
      {
        path: "registry/ui/badge-delta.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "badge-delta",
    registryDependencies: ["badge"],
    type: "ui",
  },
  "badge-delta-demo": {
    component: lazy(() => import("~/registry/example/badge-delta-demo")),
    description: "",
    files: [
      {
        path: "registry/example/badge-delta-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "badge-delta-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "badge-demo": {
    component: lazy(() => import("~/registry/example/badge-demo")),
    description: "",
    files: [
      {
        path: "registry/example/badge-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "badge-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "bar-chart-demo": {
    component: lazy(() => import("~/registry/example/bar-chart-demo")),
    description: "",
    files: [
      {
        path: "registry/example/bar-chart-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "bar-chart-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "bar-list": {
    component: lazy(() => import("~/registry/ui/bar-list")),
    description: "",
    files: [
      {
        path: "registry/ui/bar-list.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "bar-list",
    registryDependencies: undefined,
    type: "ui",
  },
  "bar-list-demo": {
    component: lazy(() => import("~/registry/example/bar-list-demo")),
    description: "",
    files: [
      {
        path: "registry/example/bar-list-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "bar-list-demo",
    registryDependencies: undefined,
    type: "example",
  },
  breadcrumb: {
    component: lazy(() => import("~/registry/ui/breadcrumb")),
    description: "",
    files: [
      {
        path: "registry/ui/breadcrumb.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "breadcrumb",
    registryDependencies: undefined,
    type: "ui",
  },
  "breadcrumb-demo": {
    component: lazy(() => import("~/registry/example/breadcrumb-demo")),
    description: "",
    files: [
      {
        path: "registry/example/breadcrumb-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "breadcrumb-demo",
    registryDependencies: undefined,
    type: "example",
  },
  button: {
    component: lazy(() => import("~/registry/ui/button")),
    description: "",
    files: [
      {
        path: "registry/ui/button.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "button",
    registryDependencies: undefined,
    type: "ui",
  },
  "button-demo": {
    component: lazy(() => import("~/registry/example/button-demo")),
    description: "",
    files: [
      {
        path: "registry/example/button-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "button-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "calendar-demo": {
    component: lazy(() => import("~/registry/example/calendar-demo")),
    description: "",
    files: [
      {
        path: "registry/example/calendar-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "calendar-demo",
    registryDependencies: undefined,
    type: "example",
  },
  callout: {
    component: lazy(() => import("~/registry/ui/callout")),
    description: "",
    files: [
      {
        path: "registry/ui/callout.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "callout",
    registryDependencies: undefined,
    type: "ui",
  },
  "callout-demo": {
    component: lazy(() => import("~/registry/example/callout-demo")),
    description: "",
    files: [
      {
        path: "registry/example/callout-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "callout-demo",
    registryDependencies: undefined,
    type: "example",
  },
  card: {
    component: lazy(() => import("~/registry/ui/card")),
    description: "",
    files: [
      {
        path: "registry/ui/card.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "card",
    registryDependencies: undefined,
    type: "ui",
  },
  "card-demo": {
    component: lazy(() => import("~/registry/example/card-demo")),
    description: "",
    files: [
      {
        path: "registry/example/card-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "card-demo",
    registryDependencies: undefined,
    type: "example",
  },
  carousel: {
    component: lazy(() => import("~/registry/ui/carousel")),
    description: "",
    files: [
      {
        path: "registry/ui/carousel.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "carousel",
    registryDependencies: undefined,
    type: "ui",
  },
  "carousel-api-demo": {
    component: lazy(() => import("~/registry/example/carousel-api-demo")),
    description: "",
    files: [
      {
        path: "registry/example/carousel-api-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "carousel-api-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "carousel-demo": {
    component: lazy(() => import("~/registry/example/carousel-demo")),
    description: "",
    files: [
      {
        path: "registry/example/carousel-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "carousel-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "carousel-orientation-demo": {
    component: lazy(
      () => import("~/registry/example/carousel-orientation-demo"),
    ),
    description: "",
    files: [
      {
        path: "registry/example/carousel-orientation-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "carousel-orientation-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "carousel-plugin-demo": {
    component: lazy(() => import("~/registry/example/carousel-plugin-demo")),
    description: "",
    files: [
      {
        path: "registry/example/carousel-plugin-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "carousel-plugin-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "carousel-size-demo": {
    component: lazy(() => import("~/registry/example/carousel-size-demo")),
    description: "",
    files: [
      {
        path: "registry/example/carousel-size-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "carousel-size-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "carousel-spacing-demo": {
    component: lazy(() => import("~/registry/example/carousel-spacing-demo")),
    description: "",
    files: [
      {
        path: "registry/example/carousel-spacing-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "carousel-spacing-demo",
    registryDependencies: undefined,
    type: "example",
  },
  charts: {
    component: lazy(() => import("~/registry/ui/charts")),
    description: "",
    files: [
      {
        path: "registry/ui/charts.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "charts",
    registryDependencies: undefined,
    type: "ui",
  },
  checkbox: {
    component: lazy(() => import("~/registry/ui/checkbox")),
    description: "",
    files: [
      {
        path: "registry/ui/checkbox.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "checkbox",
    registryDependencies: undefined,
    type: "ui",
  },
  "checkbox-demo": {
    component: lazy(() => import("~/registry/example/checkbox-demo")),
    description: "",
    files: [
      {
        path: "registry/example/checkbox-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "checkbox-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "checkbox-indeterminate-demo": {
    component: lazy(
      () => import("~/registry/example/checkbox-indeterminate-demo"),
    ),
    description: "",
    files: [
      {
        path: "registry/example/checkbox-indeterminate-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "checkbox-indeterminate-demo",
    registryDependencies: undefined,
    type: "example",
  },
  collapsible: {
    component: lazy(() => import("~/registry/ui/collapsible")),
    description: "",
    files: [
      {
        path: "registry/ui/collapsible.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "collapsible",
    registryDependencies: undefined,
    type: "ui",
  },
  "collapsible-demo": {
    component: lazy(() => import("~/registry/example/collapsible-demo")),
    description: "",
    files: [
      {
        path: "registry/example/collapsible-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "collapsible-demo",
    registryDependencies: undefined,
    type: "example",
  },
  combobox: {
    component: lazy(() => import("~/registry/ui/combobox")),
    description: "",
    files: [
      {
        path: "registry/ui/combobox.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "combobox",
    registryDependencies: undefined,
    type: "ui",
  },
  "combobox-demo": {
    component: lazy(() => import("~/registry/example/combobox-demo")),
    description: "",
    files: [
      {
        path: "registry/example/combobox-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "combobox-demo",
    registryDependencies: undefined,
    type: "example",
  },
  command: {
    component: lazy(() => import("~/registry/ui/command")),
    description: "",
    files: [
      {
        path: "registry/ui/command.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "command",
    registryDependencies: ["dialog"],
    type: "ui",
  },
  "command-demo": {
    component: lazy(() => import("~/registry/example/command-demo")),
    description: "",
    files: [
      {
        path: "registry/example/command-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "command-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "command-dialog-demo": {
    component: lazy(() => import("~/registry/example/command-dialog-demo")),
    description: "",
    files: [
      {
        path: "registry/example/command-dialog-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "command-dialog-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "context-menu": {
    component: lazy(() => import("~/registry/ui/context-menu")),
    description: "",
    files: [
      {
        path: "registry/ui/context-menu.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "context-menu",
    registryDependencies: undefined,
    type: "ui",
  },
  "context-menu-demo": {
    component: lazy(() => import("~/registry/example/context-menu-demo")),
    description: "",
    files: [
      {
        path: "registry/example/context-menu-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "context-menu-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "data-table-demo": {
    component: lazy(() => import("~/registry/example/data-table-demo")),
    description: "",
    files: [
      {
        path: "registry/example/data-table-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "data-table-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "date-picker": {
    component: lazy(() => import("~/registry/ui/date-picker")),
    description: "",
    files: [
      {
        path: "registry/ui/date-picker.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "date-picker",
    registryDependencies: ["button"],
    type: "ui",
  },
  "date-picker-demo": {
    component: lazy(() => import("~/registry/example/date-picker-demo")),
    description: "",
    files: [
      {
        path: "registry/example/date-picker-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "date-picker-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "date-range-demo": {
    component: lazy(() => import("~/registry/example/date-range-demo")),
    description: "",
    files: [
      {
        path: "registry/example/date-range-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "date-range-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "delta-bar": {
    component: lazy(() => import("~/registry/ui/delta-bar")),
    description: "",
    files: [
      {
        path: "registry/ui/delta-bar.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "delta-bar",
    registryDependencies: undefined,
    type: "ui",
  },
  "delta-bar-demo": {
    component: lazy(() => import("~/registry/example/delta-bar-demo")),
    description: "",
    files: [
      {
        path: "registry/example/delta-bar-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "delta-bar-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "demo-sidebar": {
    component: lazy(() => import("~/registry/block/demo-sidebar")),
    description: "",
    files: [
      {
        path: "registry/block/demo-sidebar.tsx",
        target: "",
        type: "component",
      },
    ],
    name: "demo-sidebar",
    registryDependencies: undefined,
    type: "block",
  },
  dialog: {
    component: lazy(() => import("~/registry/ui/dialog")),
    description: "",
    files: [
      {
        path: "registry/ui/dialog.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "dialog",
    registryDependencies: undefined,
    type: "ui",
  },
  "dialog-demo": {
    component: lazy(() => import("~/registry/example/dialog-demo")),
    description: "",
    files: [
      {
        path: "registry/example/dialog-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "dialog-demo",
    registryDependencies: undefined,
    type: "example",
  },
  drawer: {
    component: lazy(() => import("~/registry/ui/drawer")),
    description: "",
    files: [
      {
        path: "registry/ui/drawer.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "drawer",
    registryDependencies: undefined,
    type: "ui",
  },
  "drawer-demo": {
    component: lazy(() => import("~/registry/example/drawer-demo")),
    description: "",
    files: [
      {
        path: "registry/example/drawer-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "drawer-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "drawer-dialog": {
    component: lazy(() => import("~/registry/example/drawer-dialog")),
    description: "",
    files: [
      {
        path: "registry/example/drawer-dialog.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "drawer-dialog",
    registryDependencies: undefined,
    type: "example",
  },
  "dropdown-menu": {
    component: lazy(() => import("~/registry/ui/dropdown-menu")),
    description: "",
    files: [
      {
        path: "registry/ui/dropdown-menu.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "dropdown-menu",
    registryDependencies: undefined,
    type: "ui",
  },
  "dropdown-menu-demo": {
    component: lazy(() => import("~/registry/example/dropdown-menu-demo")),
    description: "",
    files: [
      {
        path: "registry/example/dropdown-menu-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "dropdown-menu-demo",
    registryDependencies: undefined,
    type: "example",
  },
  flex: {
    component: lazy(() => import("~/registry/ui/flex")),
    description: "",
    files: [
      {
        path: "registry/ui/flex.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "flex",
    registryDependencies: undefined,
    type: "ui",
  },
  "flex-demo": {
    component: lazy(() => import("~/registry/example/flex-demo")),
    description: "",
    files: [
      {
        path: "registry/example/flex-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "flex-demo",
    registryDependencies: undefined,
    type: "example",
  },
  grid: {
    component: lazy(() => import("~/registry/ui/grid")),
    description: "",
    files: [
      {
        path: "registry/ui/grid.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "grid",
    registryDependencies: undefined,
    type: "ui",
  },
  "grid-demo": {
    component: lazy(() => import("~/registry/example/grid-demo")),
    description: "",
    files: [
      {
        path: "registry/example/grid-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "grid-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "hover-card": {
    component: lazy(() => import("~/registry/ui/hover-card")),
    description: "",
    files: [
      {
        path: "registry/ui/hover-card.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "hover-card",
    registryDependencies: undefined,
    type: "ui",
  },
  "hover-card-demo": {
    component: lazy(() => import("~/registry/example/hover-card-demo")),
    description: "",
    files: [
      {
        path: "registry/example/hover-card-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "hover-card-demo",
    registryDependencies: undefined,
    type: "example",
  },
  label: {
    component: lazy(() => import("~/registry/ui/label")),
    description: "",
    files: [
      {
        path: "registry/ui/label.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "label",
    registryDependencies: undefined,
    type: "ui",
  },
  menubar: {
    component: lazy(() => import("~/registry/ui/menubar")),
    description: "",
    files: [
      {
        path: "registry/ui/menubar.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "menubar",
    registryDependencies: undefined,
    type: "ui",
  },
  "menubar-demo": {
    component: lazy(() => import("~/registry/example/menubar-demo")),
    description: "",
    files: [
      {
        path: "registry/example/menubar-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "menubar-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "mode-toggle": {
    component: lazy(() => import("~/registry/example/mode-toggle")),
    description: "",
    files: [
      {
        path: "registry/example/mode-toggle.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "mode-toggle",
    registryDependencies: undefined,
    type: "example",
  },
  "navigation-menu": {
    component: lazy(() => import("~/registry/ui/navigation-menu")),
    description: "",
    files: [
      {
        path: "registry/ui/navigation-menu.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "navigation-menu",
    registryDependencies: undefined,
    type: "ui",
  },
  "navigation-menu-demo": {
    component: lazy(() => import("~/registry/example/navigation-menu-demo")),
    description: "",
    files: [
      {
        path: "registry/example/navigation-menu-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "navigation-menu-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "number-field": {
    component: lazy(() => import("~/registry/ui/number-field")),
    description: "",
    files: [
      {
        path: "registry/ui/number-field.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "number-field",
    registryDependencies: undefined,
    type: "ui",
  },
  "number-field-demo": {
    component: lazy(() => import("~/registry/example/number-field-demo")),
    description: "",
    files: [
      {
        path: "registry/example/number-field-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "number-field-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "otp-field": {
    component: lazy(() => import("~/registry/ui/otp-field")),
    description: "",
    files: [
      {
        path: "registry/ui/otp-field.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "otp-field",
    registryDependencies: undefined,
    type: "ui",
  },
  "otp-field-demo": {
    component: lazy(() => import("~/registry/example/otp-field-demo")),
    description: "",
    files: [
      {
        path: "registry/example/otp-field-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "otp-field-demo",
    registryDependencies: undefined,
    type: "example",
  },
  pagination: {
    component: lazy(() => import("~/registry/ui/pagination")),
    description: "",
    files: [
      {
        path: "registry/ui/pagination.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "pagination",
    registryDependencies: ["button"],
    type: "ui",
  },
  "pagination-demo": {
    component: lazy(() => import("~/registry/example/pagination-demo")),
    description: "",
    files: [
      {
        path: "registry/example/pagination-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "pagination-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "pie-chart-demo": {
    component: lazy(() => import("~/registry/example/pie-chart-demo")),
    description: "",
    files: [
      {
        path: "registry/example/pie-chart-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "pie-chart-demo",
    registryDependencies: undefined,
    type: "example",
  },
  popover: {
    component: lazy(() => import("~/registry/ui/popover")),
    description: "",
    files: [
      {
        path: "registry/ui/popover.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "popover",
    registryDependencies: undefined,
    type: "ui",
  },
  "popover-demo": {
    component: lazy(() => import("~/registry/example/popover-demo")),
    description: "",
    files: [
      {
        path: "registry/example/popover-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "popover-demo",
    registryDependencies: undefined,
    type: "example",
  },
  progress: {
    component: lazy(() => import("~/registry/ui/progress")),
    description: "",
    files: [
      {
        path: "registry/ui/progress.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "progress",
    registryDependencies: ["label"],
    type: "ui",
  },
  "progress-circle": {
    component: lazy(() => import("~/registry/ui/progress-circle")),
    description: "",
    files: [
      {
        path: "registry/ui/progress-circle.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "progress-circle",
    registryDependencies: undefined,
    type: "ui",
  },
  "progress-circle-demo": {
    component: lazy(() => import("~/registry/example/progress-circle-demo")),
    description: "",
    files: [
      {
        path: "registry/example/progress-circle-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "progress-circle-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "progress-demo": {
    component: lazy(() => import("~/registry/example/progress-demo")),
    description: "",
    files: [
      {
        path: "registry/example/progress-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "progress-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "radio-group": {
    component: lazy(() => import("~/registry/ui/radio-group")),
    description: "",
    files: [
      {
        path: "registry/ui/radio-group.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "radio-group",
    registryDependencies: undefined,
    type: "ui",
  },
  "radio-group-demo": {
    component: lazy(() => import("~/registry/example/radio-group-demo")),
    description: "",
    files: [
      {
        path: "registry/example/radio-group-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "radio-group-demo",
    registryDependencies: undefined,
    type: "example",
  },
  resizable: {
    component: lazy(() => import("~/registry/ui/resizable")),
    description: "",
    files: [
      {
        path: "registry/ui/resizable.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "resizable",
    registryDependencies: undefined,
    type: "ui",
  },
  "resizable-demo": {
    component: lazy(() => import("~/registry/example/resizable-demo")),
    description: "",
    files: [
      {
        path: "registry/example/resizable-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "resizable-demo",
    registryDependencies: undefined,
    type: "example",
  },
  select: {
    component: lazy(() => import("~/registry/ui/select")),
    description: "",
    files: [
      {
        path: "registry/ui/select.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "select",
    registryDependencies: undefined,
    type: "ui",
  },
  "select-demo": {
    component: lazy(() => import("~/registry/example/select-demo")),
    description: "",
    files: [
      {
        path: "registry/example/select-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "select-demo",
    registryDependencies: undefined,
    type: "example",
  },
  separator: {
    component: lazy(() => import("~/registry/ui/separator")),
    description: "",
    files: [
      {
        path: "registry/ui/separator.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "separator",
    registryDependencies: undefined,
    type: "ui",
  },
  "separator-demo": {
    component: lazy(() => import("~/registry/example/separator-demo")),
    description: "",
    files: [
      {
        path: "registry/example/separator-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "separator-demo",
    registryDependencies: undefined,
    type: "example",
  },
  sheet: {
    component: lazy(() => import("~/registry/ui/sheet")),
    description: "",
    files: [
      {
        path: "registry/ui/sheet.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "sheet",
    registryDependencies: undefined,
    type: "ui",
  },
  "sheet-demo": {
    component: lazy(() => import("~/registry/example/sheet-demo")),
    description: "",
    files: [
      {
        path: "registry/example/sheet-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "sheet-demo",
    registryDependencies: undefined,
    type: "example",
  },
  sidebar: {
    component: lazy(() => import("~/registry/ui/sidebar")),
    description: "",
    files: [
      {
        path: "registry/ui/sidebar.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "sidebar",
    registryDependencies: [
      "button",
      "separator",
      "sheet",
      "skeleton",
      "text-field",
      "tooltip",
      "use-mobile",
    ],
    type: "ui",
  },
  "sidebar-01": {
    component: lazy(() => import("~/registry/block/sidebar-01")),
    description: "A simple sidebar with navigation grouped by section",
    files: [
      {
        path: "registry/block/sidebar-01/index.tsx",
        target: "app/dashboard/page.tsx",
        type: "page",
      },
      {
        path: "registry/block/sidebar-01/components/app-sidebar.tsx",
        target: "",
        type: "component",
      },
      {
        path: "registry/block/sidebar-01/components/search-form.tsx",
        target: "",
        type: "component",
      },
      {
        path: "registry/block/sidebar-01/components/version-switcher.tsx",
        target: "",
        type: "component",
      },
    ],
    name: "sidebar-01",
    registryDependencies: [
      "sidebar",
      "breadcrumb",
      "separator",
      "label",
      "dropdown-menu",
    ],
    type: "block",
  },
  skeleton: {
    component: lazy(() => import("~/registry/ui/skeleton")),
    description: "",
    files: [
      {
        path: "registry/ui/skeleton.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "skeleton",
    registryDependencies: undefined,
    type: "ui",
  },
  "skeleton-demo": {
    component: lazy(() => import("~/registry/example/skeleton-demo")),
    description: "",
    files: [
      {
        path: "registry/example/skeleton-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "skeleton-demo",
    registryDependencies: undefined,
    type: "example",
  },
  slider: {
    component: lazy(() => import("~/registry/ui/slider")),
    description: "",
    files: [
      {
        path: "registry/ui/slider.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "slider",
    registryDependencies: ["label"],
    type: "ui",
  },
  "slider-demo": {
    component: lazy(() => import("~/registry/example/slider-demo")),
    description: "",
    files: [
      {
        path: "registry/example/slider-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "slider-demo",
    registryDependencies: undefined,
    type: "example",
  },
  sonner: {
    component: lazy(() => import("~/registry/ui/sonner")),
    description: "",
    files: [
      {
        path: "registry/ui/sonner.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "sonner",
    registryDependencies: undefined,
    type: "ui",
  },
  "sonner-demo": {
    component: lazy(() => import("~/registry/example/sonner-demo")),
    description: "",
    files: [
      {
        path: "registry/example/sonner-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "sonner-demo",
    registryDependencies: undefined,
    type: "example",
  },
  switch: {
    component: lazy(() => import("~/registry/ui/switch")),
    description: "",
    files: [
      {
        path: "registry/ui/switch.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "switch",
    registryDependencies: undefined,
    type: "ui",
  },
  "switch-demo": {
    component: lazy(() => import("~/registry/example/switch-demo")),
    description: "",
    files: [
      {
        path: "registry/example/switch-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "switch-demo",
    registryDependencies: undefined,
    type: "example",
  },
  table: {
    component: lazy(() => import("~/registry/ui/table")),
    description: "",
    files: [
      {
        path: "registry/ui/table.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "table",
    registryDependencies: undefined,
    type: "ui",
  },
  "table-demo": {
    component: lazy(() => import("~/registry/example/table-demo")),
    description: "",
    files: [
      {
        path: "registry/example/table-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "table-demo",
    registryDependencies: undefined,
    type: "example",
  },
  tabs: {
    component: lazy(() => import("~/registry/ui/tabs")),
    description: "",
    files: [
      {
        path: "registry/ui/tabs.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "tabs",
    registryDependencies: undefined,
    type: "ui",
  },
  "tabs-demo": {
    component: lazy(() => import("~/registry/example/tabs-demo")),
    description: "",
    files: [
      {
        path: "registry/example/tabs-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "tabs-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "text-field": {
    component: lazy(() => import("~/registry/ui/text-field")),
    description: "",
    files: [
      {
        path: "registry/ui/text-field.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "text-field",
    registryDependencies: undefined,
    type: "ui",
  },
  "text-field-demo": {
    component: lazy(() => import("~/registry/example/text-field-demo")),
    description: "",
    files: [
      {
        path: "registry/example/text-field-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "text-field-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "text-field-error-demo": {
    component: lazy(() => import("~/registry/example/text-field-error-demo")),
    description: "",
    files: [
      {
        path: "registry/example/text-field-error-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "text-field-error-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "text-field-textarea-demo": {
    component: lazy(
      () => import("~/registry/example/text-field-textarea-demo"),
    ),
    description: "",
    files: [
      {
        path: "registry/example/text-field-textarea-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "text-field-textarea-demo",
    registryDependencies: undefined,
    type: "example",
  },
  timeline: {
    component: lazy(() => import("~/registry/ui/timeline")),
    description: "",
    files: [
      {
        path: "registry/ui/timeline.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "timeline",
    registryDependencies: undefined,
    type: "ui",
  },
  "timeline-demo": {
    component: lazy(() => import("~/registry/example/timeline-demo")),
    description: "",
    files: [
      {
        path: "registry/example/timeline-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "timeline-demo",
    registryDependencies: undefined,
    type: "example",
  },
  toast: {
    component: lazy(() => import("~/registry/ui/toast")),
    description: "",
    files: [
      {
        path: "registry/ui/toast.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "toast",
    registryDependencies: undefined,
    type: "ui",
  },
  "toast-demo": {
    component: lazy(() => import("~/registry/example/toast-demo")),
    description: "",
    files: [
      {
        path: "registry/example/toast-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "toast-demo",
    registryDependencies: undefined,
    type: "example",
  },
  toggle: {
    component: lazy(() => import("~/registry/ui/toggle")),
    description: "",
    files: [
      {
        path: "registry/ui/toggle.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "toggle",
    registryDependencies: undefined,
    type: "ui",
  },
  "toggle-demo": {
    component: lazy(() => import("~/registry/example/toggle-demo")),
    description: "",
    files: [
      {
        path: "registry/example/toggle-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "toggle-demo",
    registryDependencies: undefined,
    type: "example",
  },
  "toggle-group": {
    component: lazy(() => import("~/registry/ui/toggle-group")),
    description: "",
    files: [
      {
        path: "registry/ui/toggle-group.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "toggle-group",
    registryDependencies: undefined,
    type: "ui",
  },
  "toggle-group-demo": {
    component: lazy(() => import("~/registry/example/toggle-group-demo")),
    description: "",
    files: [
      {
        path: "registry/example/toggle-group-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "toggle-group-demo",
    registryDependencies: undefined,
    type: "example",
  },
  tooltip: {
    component: lazy(() => import("~/registry/ui/tooltip")),
    description: "",
    files: [
      {
        path: "registry/ui/tooltip.tsx",
        target: "",
        type: "ui",
      },
    ],
    name: "tooltip",
    registryDependencies: undefined,
    type: "ui",
  },
  "tooltip-demo": {
    component: lazy(() => import("~/registry/example/tooltip-demo")),
    description: "",
    files: [
      {
        path: "registry/example/tooltip-demo.tsx",
        target: "",
        type: "example",
      },
    ],
    name: "tooltip-demo",
    registryDependencies: undefined,
    type: "example",
  },
};
