// Auto-generated by scripts/build-icons.ts
export {
  IconArrowLeft,
  IconArrowRight,
  IconCheck,
  IconChevronDown,
  IconChevronRight,
  IconChevronUp,
  IconCopy,
  IconDots,
  IconExclamationCircle,
  IconLoader,
  IconMinus,
  IconPlus,
  IconShare,
  IconShoppingBag,
  IconTrash
} from "@tabler/icons-solidjs"
